import 'package:get/get.dart';

class Locations {
 static const List<String> governorates = [
  'Damascus',
  'Homs',
  'Idlib',
  'Hama',
  'Aleppo',
  'Daraa',
  'Qwnitra',
  'Latakia',
  'Tartous',
  'Dear Al-Zoor',
  'Al-Swida',
  'Al-Raqa',
  'Al-Hasaka',
 ];

 static const List<String> cites = [
  "Dhadeel",
  "Al Yarmouk",
  "Jrmana",
  "Baramka",
  "Mhajreen",
  "Bagdad.S",
  "Midan",
  "Rokn Aldeen",
  "Mazah",
  "Ar Rastan",
  "Tadmur",
  "Al Qusayr",
  "Tallbisah",
  "Al Qaryatayn",
  "Tallkalakh",
  "Kafr Laha",
  "As Sukhnah",
  "Shin",
  "Tall Dhahab",
  "Mahin",
  "Ma`arrat an Nu`man",
  "Khan Shaykhun",
  "Jisr ash Shughur",
  "Saraqib",
  "Ma`arratmisrin",
  "Kafr Nubl",
  "Salqin",
  "Harim",
  "Binnish",
  "Sarmada",
  'Masyaf',
  'Al-Salamiyah',
  'Mhardeh',
  'Al-Suqaylabiyah',
  'Azaz',
  'Manbij',
  'Al-Bab',
  'Jarabulus',
  'Izra',
  'Nawa',
  'Jasim',
  'Al-Sanamayn',
  'Khan Arnabah',
  'Madīnat al-Baath',
  'Jubbata al-Khashab',
  'Al-Rafid',
  'Jableh',
  'Al-Haffah',
  'Qardaha',
  'Rabia',
  'Baniyas',
  'Safita',
  'Al-Sheikh Badr',
  'Dreikish',
  'Al-Mayadin',
  'Al-Bukamal',
  'Al-Shaddadah',
  'Al-Suwar',
  'Shahba',
  'Salkhad',
  'Al-Qurayya',
  'Al-Mazraa',
  'Al-Thawrah',
  'Al-Sabkha',
  'Maadan',
  'Al-Karamah',
  'Qamishli',
  'Ras al-Ayn',
  'Al-Malikiyah',
  'Shaddadi',
 ];

}
